version: "3.8"

services:
  app:
    build:
      context: .
      network: host 
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: user1
      DB_PASSWORD: password1
      DB_NAME: product-api
    restart: on-failure

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: user1
      POSTGRES_PASSWORD: password1
      POSTGRES_DB: product-api
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata:
